### ISSUE TITLE
看大佬的获取方式好复杂啊,提点意见

### ISSUE THREAD

**Issue by daofeng2015** [Henryhaohao/Bilibili_video_download#22]
获取cid的api为 https://api.bilibili.com/x/web-interface/view?aid=47476691 aid后面为av号
下载链接api为 https://api.bilibili.com/x/player/playurl?cid=86427312&avid=49357810 cid为上面获取到的 avid为输入的av号
不需要什么appkey的，那些都是m端用的
如果需要大会员的传入自己登陆的cookie就行了

**Comment by Henryhaohao** [comment]
哈哈的确,直接用这个API很方便呀~:smile:
但是怎么获取不同画质的视频下载链接呢,还望指点,默认就直接是最高质量的 @daofeng2015

**Comment by blogwy** [comment]
https://api.bilibili.com/x/player/playurl?avid=44743619&cid=78328965&qn=80&otype=json
qn参数就是清晰度
可选值：
80   高清1080P
64   高清720P
32   清晰480P
16   流畅360P

上面是普通会员可选的清晰度。然后，大会员720+好像是72，1080+ 忘了。

**Comment by Henryhaohao** [comment]
谢谢老哥啦~那我就用这个接口写个新代码了:smile: @blogwy

**Comment by Henryhaohao** [comment]
哈哈,不好意思大家~
今早有大佬提醒我了: 不管是什么视频 下载之后都是最低清晰度 哪怕选择了80也是只有480p的分辨率
我试了一下还真的是这样, 昨天都没注意到呢
所以我还是改回原来加密接口的版本吧, 可以下720,1080的视频
最后, 哈哈还是要感谢两位大大:smile: @daofeng2015 @blogwy

**Comment by blogwy** [comment]
请求的时候header要加上这个:
headers: {
          'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko/20100101 Firefox/56.0',
          'Host': 'api.bilibili.com',
          'Cookie': 'SESSDATA=bd125cdd%2C1554519358%2C6d4df231'
        }
SESSDATA从登录的cookie里面取，你试试。我以前就是这么干的。但是不知道现在还可以吗。

**Comment by Henryhaohao** [comment]
嗯 加上cookie的确可以获取到720p及以上的清晰度了;
谢谢大佬指点! @blogwy

**Comment by daofeng2015** [comment]
需要登录的.传入cookie就行了,b站默认游客只能获取到480p，登录720和1080,大会员可以720p/60，1080p/60
