### ISSUE TITLE
Linux下运行出错

### ISSUE THREAD

**Issue by SuzukiHonoka** [Henryhaohao/Bilibili_video_download#31]
相关依赖已经安装：
root@starx:/home/starx/Bilibili_video_download# python3 bilibili_video_download_v1.py 
Traceback (most recent call last):
  File "bilibili_video_download_v1.py", line 167, in <module>
    print('*' * 30 + 'B\u7ad9\u89c6\u9891\u4e0b\u8f7d\u5c0f\u52a9\u624b' + '*' * 30)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-38: ordinal not in range(128)

**Comment by Henryhaohao** [comment]
需要将文件指定为utf-8编码
解决办法:   [http://blog.sina.com.cn/s/blog_64a3795a01018vyp.html](url) @SuzukiHonoka
