### ISSUE TITLE
输入视频av号后出错

### ISSUE THREAD

**Issue by chn-lee-yumi** [Henryhaohao/Bilibili_video_download#34]
➜  Bilibili_video_download git:(master) python3 bilibili_video_download_v1.py
******************************B站视频下载小助手******************************
请输入您要下载的B站av号或者视频链接地址:av50596322
Traceback (most recent call last):
  File "bilibili_video_download_v1.py", line 176, in <module>
    start_url = 'https://api.bilibili.com/x/web-interface/view?aid=' + re.search(r'/av(\d+)/*', start).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by chn-lee-yumi** [comment]
环境：
MacOS
Python 3.7.3

**Comment by Henryhaohao** [comment]
输入完整视频链接如: https://www.bilibili.com/video/av50596322
或者直接输入av号就行了: 50596322  , 前面不用加av的 @chn-lee-yumi

**Comment by chn-lee-yumi** [comment]
@Henryhaohao 谢谢，建议在文档里面说清楚一点（可以举个例子）

**Comment by chn-lee-yumi** [comment]
谢谢，我仔细翻了下readme，里面写了，我看漏了。
