### ISSUE TITLE
能否用配置文件的办法读取cookie呢

### ISSUE THREAD

**Issue by daofeng2015** [Henryhaohao/Bilibili_video_download#53]
每次改代码贼累....直接从配置文件里读就行了

**Comment by SunriseCai** [comment]
能你妈



---原始邮件---
发件人: "蒋"<notifications@github.com&gt;
发送时间: 2019年9月1日(星期日) 晚上11:18
收件人: "Henryhaohao/Bilibili_video_download"<Bilibili_video_download@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Henryhaohao/Bilibili_video_download] 能否用配置文件的办法读取cookie呢 (#53)



每次改代码贼累....直接从配置文件里读就行了
