### ISSUE TITLE
没梯子的我死在了ffmpeg上

### ISSUE THREAD

**Issue by poisonousfish** [Henryhaohao/Bilibili_video_download#74]
ffmpeg.win32.exe 下不下来 
在github下根本走不动
大佬可以考虑下导出可以执行文件呀 或者借个梯子

**Comment by iosmers** [comment]
我mac的系统，试了很久成功了，你可以试试这个
https://github.com/imageio/imageio-binaries/tree/master/ffmpeg

**Comment by poisonousfish** [comment]
这个我试过，我试了好几次 下了几MB，就卡住了。最后我把它镜像到码云上了，可以下载了，不过码云真的烦，不停的要求你输入验证码，不知道的人还以为我训练AI呢

**Comment by shaolingongfuhao** [comment]
用码云把ffmpeg下好了，但是怎么用呢，点击了没反应

**Comment by poisonousfish** [comment]
> 用码云把ffmpeg下好了，但是怎么用呢，点击了没反应

时间有点久远了，我记得放到对应的文件夹，就可以正常运行了
