### ISSUE TITLE
请问下载时可以直接下载mp4格式吗？

### ISSUE THREAD

**Issue by xuejianxianzun** [Henryhaohao/Bilibili_video_download#88]
直接下载下来的是flv，没有预览图，mp4格式可以预览。
不知道通过较为简单的修改代码来实现？如果比较麻烦的话那我就用下载之后再转换吧，求教~

**Comment by dengmin** [comment]
可以的 , 请看看 http://bilibili.syyhc.com 目前我只是做了高清视频下载 1080p哦

**Comment by xuejianxianzun** [comment]
> 可以的 , 请看看 http://bilibili.syyhc.com 目前我只是做了高清视频下载 1080p哦

试了一下很好，感谢~

**Comment by yhhwpp** [comment]
@ dengmin 为什么接口没有mp4

**Comment by yhhwpp** [comment]
> 可以的 , 请看看 http://bilibili.syyhc.com 目前我只是做了高清视频下载 1080p哦

请教下这个高清的mp4文件是如何得到的，我通过接口`api.bilibili.com/x/player/playurl?cid=262011033`只能获取flv格式的

![image](https://user-images.githubusercontent.com/7929656/123766562-62254c80-d8f9-11eb-8910-37c49632556d.png)
