### ISSUE TITLE
既然这么多人都在发自己的东西那我也来一个吧,C++版哔哩哔哩下载器支持登录,无需ffmpeg,下载格式flv,支持下载&转换弹幕,支持下载/转换CC字幕,正在持续更新中

### ISSUE THREAD

**Issue by mwx2006** [Henryhaohao/Bilibili_video_download#90]
既然这么多人都在发自己的东西那我也来一个吧,C++版哔哩哔哩下载器支持登录,无需ffmpeg,下载格式flv,支持下载&转换弹幕,支持下载/转换CC字幕,正在持续更新中，[下载链接](https://nd.m-dr.cc)

[Linux版](https://mwx.coding.net/s/5c2fb206-255d-4ae8-9d63-8b6e9c6f41b7)
依赖:jsoncpp,libcurl,openssl

**Comment by stariver1862** [comment]
很喜欢这个C++版本，可以有个选项不要弹幕么？或者代码能放github上我自己来修改？

**Comment by stariver1862** [comment]
解决了，把弹幕文件删掉就可以了。再赞一下这个c++版本！

**Comment by EthanHsiung** [comment]
能一键设定下载所有分P以及下载的清晰度吗？

**Comment by kedyao** [comment]
> 既然这么多人都在发自己的东西那我也来一个吧,C++版哔哩哔哩下载器支持登录,无需ffmpeg,下载格式flv,支持下载&转换弹幕,支持下载/转换CC字幕,正在持续更新中，[下载链接](https://nd.m-dr.cc)
> 
> [Linux版](https://mwx.coding.net/s/5c2fb206-255d-4ae8-9d63-8b6e9c6f41b7)
> 依赖:jsoncpp,libcurl,openssl

目前无法进行登录

**Comment by CoderCIRNO** [comment]
很强，方便开源吗，想学习下
